### ISSUE TITLE
没有声音

### ISSUE THREAD

**Issue by kunbile00** [xmtggh/VideoCalling#7]
您好，我想问问视频过程中没有声音是什么原因呢？

**Comment by xmtggh** [comment]
可能调试中注释掉了代码

**Comment by kunbile00** [comment]
请问可以加您QQ或者微信吗？最近的项目中需要用到这个功能，希望可以多多跟您交流学习！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xmtggh"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 上午9:18
收件人:&nbsp;"xmtggh/VideoCalling"<VideoCalling@noreply.github.com&gt;;
抄送:&nbsp;"冷月葬花"<865147933@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xmtggh/VideoCalling] 没有声音 (#7)




可能调试中注释掉了代码

**Comment by xmtggh** [comment]
@kunbile00 微信qq是私人的，若是有什么项目问题直接在这里提问，我要是能解惑一定会回复

**Comment by kunbile00** [comment]
好的，谢谢您！我在您的代码中没有找到关于您注释的语音的代码，您可以帮我看看吗？辛苦您了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xmtggh"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 上午9:23
收件人:&nbsp;"xmtggh/VideoCalling"<VideoCalling@noreply.github.com&gt;;
抄送:&nbsp;"冷月葬花"<865147933@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xmtggh/VideoCalling] 没有声音 (#7)




@kunbile00 微信qq是私人的，若是有什么项目问题直接在这里提问，我要是能解惑一定会回复

**Comment by xmtggh** [comment]
@kunbile00 若是代码没问题就是其他问题了，看也没有用，你自己检测一下音频是否有录音回调，有没有接收正常，排除一下问题

**Comment by kunzaigithub** [comment]
419776791我QQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kunbile00"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 上午9:21
收件人:&nbsp;"xmtggh/VideoCalling"<VideoCalling@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [xmtggh/VideoCalling] 没有声音 (#7)



请问可以加您QQ或者微信吗？最近的项目中需要用到这个功能，希望可以多多跟您交流学习！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"xmtggh"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年11月5日(星期二) 上午9:18 
 收件人:&amp;nbsp;"xmtggh/VideoCalling"<VideoCalling@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"冷月葬花"<865147933@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xmtggh/VideoCalling] 没有声音 (#7) 
 
 
 
 
 可能调试中注释掉了代码

**Comment by kunbile00** [comment]
E/AndroidRuntime: FATAL EXCEPTION: Thread-728
&nbsp; &nbsp; Process: com.ggh.video, PID: 28872
&nbsp; &nbsp; java.lang.IndexOutOfBoundsException
&nbsp; &nbsp; &nbsp; &nbsp; at java.util.LinkedList.remove(LinkedList.java:660)
&nbsp; &nbsp; &nbsp; &nbsp; at java.util.Collections$SynchronizedList.remove(Collections.java:613)
&nbsp; &nbsp; &nbsp; &nbsp; at com.ggh.video.decode.AudioDecoder.run(AudioDecoder.java:72)
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Thread.run(Thread.java:833)

//定位在这一行
AudioData encodedData = dataList.remove(0);
我参考您之前的代码进行修改后，一打开语音就报这个错。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kunzaigithub"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 上午9:28
收件人:&nbsp;"xmtggh/VideoCalling"<VideoCalling@noreply.github.com&gt;;
抄送:&nbsp;"冷月葬花"<865147933@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xmtggh/VideoCalling] 没有声音 (#7)



419776791我QQ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"kunbile00"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年11月5日(星期二) 上午9:21 
 收件人:&amp;nbsp;"xmtggh/VideoCalling"<VideoCalling@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [xmtggh/VideoCalling] 没有声音 (#7) 
 
 
 
 请问可以加您QQ或者微信吗？最近的项目中需要用到这个功能，希望可以多多跟您交流学习！  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"xmtggh"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2019年11月5日(星期二) 上午9:18  
  收件人:&amp;amp;nbsp;"xmtggh/VideoCalling"<VideoCalling@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"冷月葬花"<865147933@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [xmtggh/VideoCalling] 没有声音 (#7)  
   
   
   
   
  可能调试中注释掉了代码
