### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by unicorn1009** [xmtggh/VideoCalling#8]
测试了三台设备，有两台设备点开就闪退，一台安卓7.0的，一台安卓9.0的，安卓4.4的设备不闪退

**Comment by xmtggh** [comment]
@unicorn1009 贴log

**Comment by unicorn1009** [comment]
2019-11-19 17:04:25.484 9849-9849/? E/HAL: PATH3 /odm/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:25.484 9840-9840/? E/HAL: PATH3 /odm/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:25.485 9840-9840/? E/HAL: PATH2 /vendor/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:25.485 9849-9849/? E/HAL: PATH2 /vendor/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:25.485 9840-9840/? E/HAL: PATH1 /system/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:25.485 9849-9849/? E/HAL: PATH1 /system/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:25.485 9840-9840/? E/HAL: PATH3 /odm/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:25.485 9849-9849/? E/HAL: PATH3 /odm/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:25.485 9840-9840/? E/HAL: PATH2 /vendor/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:25.485 9849-9849/? E/HAL: PATH2 /vendor/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:25.485 9840-9840/? E/HAL: PATH1 /system/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:25.485 9849-9849/? E/HAL: PATH1 /system/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:26.247 1668-2927/? E/WifiService: Permission denial: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
2019-11-19 17:04:26.253 1668-3692/? E/WifiService: Permission denial: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
2019-11-19 17:04:26.741 6751-6791/? E/zeus-AndroidUtils-[WorkingThread]: top : com.miui.home
    
    --------- beginning of system
2019-11-19 17:04:26.796 467-2699/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-11-19 17:04:27.515 467-2699/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-11-19 17:04:30.671 13724-9965/? E/WakePathManager: UpdateWakePathTask.doInBackground: isWifiNetwork==false
2019-11-19 17:04:31.074 3607-3651/? E/BoutiqueGameRT: [doInstallSuccReport] di is NULL OR di.mStatus != DOWNLOAD_STATUS_SUCCEED OR SENDED!
2019-11-19 17:04:31.651 9976-9976/? E/HAL: PATH3 /odm/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:31.651 9976-9976/? E/HAL: PATH2 /vendor/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:31.651 9976-9976/? E/HAL: PATH1 /system/lib64/hw/memtrack.qcom.so
2019-11-19 17:04:31.651 9976-9976/? E/HAL: PATH3 /odm/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:31.651 9976-9976/? E/HAL: PATH2 /vendor/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:31.651 9976-9976/? E/HAL: PATH1 /system/lib64/hw/memtrack.msm8953.so
2019-11-19 17:04:31.771 467-2699/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-11-19 17:04:31.935 10084-10084/com.ggh.video E/art: No implementation found for int com.gyz.voipdemo_speex.util.Speex.open(int) (tried Java_com_gyz_voipdemo_1speex_util_Speex_open and Java_com_gyz_voipdemo_1speex_util_Speex_open__I)
2019-11-19 17:04:31.937 10084-10084/com.ggh.video E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ggh.video, PID: 10084
    java.lang.UnsatisfiedLinkError: No implementation found for int com.gyz.voipdemo_speex.util.Speex.open(int) (tried Java_com_gyz_voipdemo_1speex_util_Speex_open and Java_com_gyz_voipdemo_1speex_util_Speex_open__I)
        at com.gyz.voipdemo_speex.util.Speex.open(Native Method)
        at com.gyz.voipdemo_speex.util.Speex.init(Speex.java:28)
        at com.ggh.video.App.onCreate(App.java:20)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5530)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1611)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
2019-11-19 17:04:31.970 558-558/? E/lowmemorykiller: Error opening /proc/10084/oom_score_adj; errno=2
2019-11-19 17:04:32.325 10062-10062/? E/MnsTracer(MiLinkSDK)(GameCenter): main=>Client File Trace Level Changed = 63
2019-11-19 17:04:32.325 10062-10062/? E/MnsTracer(MiLinkSDK)(GameCenter): main=>Client Logcat Trace Level Changed = 63
2019-11-19 17:04:32.366 10062-10151/? E/MnsTracer(MiLinkSDK)(GameCenter): RxCachedThreadScheduler-1=>File Trace Level Changed = 56
2019-11-19 17:04:32.366 10062-10151/? E/MnsTracer(MiLinkSDK)(GameCenter): RxCachedThreadScheduler-1=>Logcat Trace Level Changed = 56
2019-11-19 17:04:32.427 10062-10062/? E/Report: DIndexManager init
2019-11-19 17:04:32.485 10062-10168/? E/TAG: com.android.org.conscrypt.OpenSSLSocketFactoryImpl@87fe06
2019-11-19 17:04:32.492 10062-10062/? E/MnsTracer(MiLinkSDK)(GameCenter): main=>Logcat Trace Level Changed = 56
2019-11-19 17:04:32.493 10062-10062/? E/MnsTracer(MiLinkSDK)(GameCenter): main=>Logcat Trace Level Changed = 56
2019-11-19 17:04:32.493 10062-10062/? E/MnsTracer(MiLinkSDK)(GameCenter): main=>File Trace Level Changed = 56
2019-11-19 17:04:32.494 10062-10062/? E/MnsTracer(MiLinkSDK)(GameCenter): main=>File Trace Level Changed = 56
2019-11-19 17:04:32.494 10062-10062/? E/MiLinkClient(MiLinkSDK)(GameCenter): main=>dangerous!!!!getRemoteService in main Thread is not safe!!!
2019-11-19 17:04:32.534 10062-10062/? E/MiDJSdk: Appid : 4172, Appkey : 274ef47a-a683-09d6-fdc8-50b4365599e3, package name : com.xiaomi.gamecenter
2019-11-19 17:04:32.545 10062-10186/? E/MiLinkClient(MiLinkSDK)(GameCenter): Thread-10=>getRemoteService, but remoteService = null, stopCount=0
2019-11-19 17:04:32.546 10062-10186/? E/MiLinkClient(MiLinkSDK)(GameCenter): Thread-10=>try startService, startCount=1
2019-11-19 17:04:32.576 10062-10166/? E/GameCenterAPP: Channel : default
2019-11-19 17:04:32.580 10062-10186/? E/MiLinkClient(MiLinkSDK)(GameCenter): Thread-10=>startService ComponentName = ComponentInfo{com.xiaomi.gamecenter/com.mi.milink.sdk.service.MiLinkService}
2019-11-19 17:04:32.592 10062-10186/? E/MiLinkClient(MiLinkSDK)(GameCenter): Thread-10=>start service success
2019-11-19 17:04:32.796 10062-10235/? E/[No:4]SessionForSimpleChannel_20005(MiLinkSDK)(misdk): Thread-19=>connect to [ sIP=120.92.165.31, sPort=14000, pIP=null, pPort=0, protocol=tcp, type=recently ]
2019-11-19 17:04:32.798 10062-10234/? E/[No:6]SessionForSimpleChannel_20005(MiLinkSDK)(misdk): Thread-20=>connect to [ sIP=120.92.165.31, sPort=14000, pIP=null, pPort=0, protocol=tcp, type=recently ]
2019-11-19 17:04:32.839 10062-10236/? E/[No:5]SessionForSimpleChannel_20005(MiLinkSDK)(misdk): Thread-21=>connect to [ sIP=120.92.165.31, sPort=14000, pIP=null, pPort=0, protocol=tcp, type=recently ]
2019-11-19 17:04:32.851 10062-10235/? E/SessionManager(MiLinkSDK)(misdk): Thread-19=>SessionManager created, milinkversion=2_1
2019-11-19 17:04:32.909 10062-10062/? E/migamesdk_plugin: build time:20170714164513,branch:mistat_170713,commitid:7b7394ef2e0b566b2cfdd40a8c6a94f773ec2cf0,version:31
2019-11-19 17:04:32.925 10062-10062/? E/MnsTracer(MiLinkSDK)(misdk): main=>Logcat Trace Level Changed = 56
2019-11-19 17:04:32.925 10062-10062/? E/MnsTracer(MiLinkSDK)(misdk): main=>Logcat Trace Level Changed = 56
2019-11-19 17:04:32.926 10062-10062/? E/MnsTracer(MiLinkSDK)(misdk): main=>File Trace Level Changed = 56
2019-11-19 17:04:32.926 10062-10062/? E/MnsTracer(MiLinkSDK)(misdk): main=>File Trace Level Changed = 56
2019-11-19 17:04:32.939 10190-10190/? E/MiGameSDK: >>>>>>>>>>>>MiStatInterface isHasInitialize:true
2019-11-19 17:04:33.045 10062-10062/? E/MiLinkClient(MiLinkSDK)(misdk): main=>onServiceConnected()
2019-11-19 17:04:33.053 10062-10062/? E/MiLinkClient(MiLinkSDK)(misdk): main=>onServiceConnected got a binder
2019-11-19 17:04:33.815 10190-10190/? E/MnsTracer(MiLinkSDK)(misdk): main=>File Trace Level Changed = 63
2019-11-19 17:04:33.816 10190-10190/? E/MnsTracer(MiLinkSDK)(misdk): main=>Logcat Trace Level Changed = 63
2019-11-19 17:04:33.941 598-603/? E/rpmb_emmc: ----------------------------rpmb_emmc_read-----------------------------
2019-11-19 17:04:33.975 598-603/? E/rpmb_emmc: ----------------------------rpmb_emmc_read-----------------------------
2019-11-19 17:04:34.006 598-603/? E/rpmb_emmc: ----------------------------rpmb_emmc_read-----------------------------
2019-11-19 17:04:34.109 558-558/? E/lowmemorykiller: Error writing /proc/9296/oom_score_adj; errno=22
2019-11-19 17:04:34.109 558-558/? E/lowmemorykiller: Error writing /proc/9472/oom_score_adj; errno=22
2019-11-19 17:04:34.109 558-558/? E/lowmemorykiller: Error writing /proc/9730/oom_score_adj; errno=22
2019-11-19 17:04:34.158 558-558/? E/lowmemorykiller: Error writing /proc/9296/oom_score_adj; errno=22
2019-11-19 17:04:34.158 558-558/? E/lowmemorykiller: Error writing /proc/9472/oom_score_adj; errno=22
2019-11-19 17:04:34.158 558-558/? E/lowmemorykiller: Error writing /proc/9730/oom_score_adj; errno=22
2019-11-19 17:04:34.187 10062-10062/? E/ServiceDeviceInfoHelper: connected
2019-11-19 17:04:34.240 10062-10062/? E/ServiceDeviceInfoHelper: getDeviceId after connect : 6OJgav6GOiu7Bq1S
2019-11-19 17:04:34.396 10062-10457/? E/[No:8]SessionForSimpleChannel_20005(MiLinkSDK)(misdk): Thread-48=>connect to [ sIP=120.92.165.31, sPort=14000, pIP=null, pPort=0, protocol=tcp, type=recently ]

**Comment by unicorn1009** [comment]
> @unicorn1009 贴log

刚学安卓。。不太懂，实在不好意思

**Comment by xmtggh** [comment]
@unicorn1009 加载speex报错了 你把App中的 Speex.getInstance().init(); 注释掉试试，so没加载进去

**Comment by unicorn1009** [comment]
注释掉后可以进入应用了，但是每次点击视频测试按钮的时候都会闪退。
2019-11-19 17:22:26.952 1384-3171/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.ggh.video/com.ggh.video.VideoTalkActivity/1
2019-11-19 17:22:26.958 1384-3171/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.ggh.video/com.ggh.video.VideoTalkActivity/1
2019-11-19 17:22:26.969 1384-3171/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.ggh.video/com.ggh.video.VideoTalkActivity/1
2019-11-19 17:22:27.005 954-2143/? E/OMX-VDEC-1080P: Unsupported output color format for c2d (2141391876)
2019-11-19 17:22:27.005 954-2143/? E/OMX-VDEC-1080P: Setting color format failed
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: get_parameter: unknown param 7f000046
2019-11-19 17:22:27.011 954-2143/? E/OMXNodeInstance: getParameter(0xf2f3aec4:qcom.decoder.avc, ??(0x7f000046)) ERROR: UnsupportedIndex(0x8000101a)
2019-11-19 17:22:27.017 954-2143/? E/OMXNodeInstance: getParameter(0xf2f3aec4:qcom.decoder.avc, ??(0x7f000044)) ERROR: UnsupportedSetting(0x80001019)
2019-11-19 17:22:27.039 22521-22521/com.ggh.video E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ggh.video, PID: 22521
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ggh.video-rqVFpNiQ4z7iMGjMgK194w==/base.apk"],nativeLibraryDirectories=[/data/app/com.ggh.video-rqVFpNiQ4z7iMGjMgK194w==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libx264encoder.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at example.sszpf.x264.x264sdk.<clinit>(x264sdk.java:32)
        at com.ggh.video.encode.X264Encoder.initEncode(X264Encoder.java:39)
        at com.ggh.video.encode.X264Encoder.<init>(X264Encoder.java:22)
        at com.ggh.video.VideoTalkActivity.onCreate(VideoTalkActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2019-11-19 17:22:27.049 2737-2787/? E/octvm_klo: open /data/system/dropbox/system_app_crash@1573815354907.txt for read error, No such file or directory
2019-11-19 17:22:27.074 954-2143/? E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
2019-11-19 17:22:27.075 1384-1806/? E/InputDispatcher: channel 'd3ee469 com.ggh.video/com.ggh.video.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-11-19 17:22:27.088 1384-3171/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.miui.home/com.miui.home.launcher.Launcher/41201228
2019-11-19 17:22:27.407 5294-5294/? E/Launcher: changeViewByFsGestureState,  view=FitSystemWindowView,  alpha=1.0,  scale=1.0
2019-11-19 17:22:27.407 5294-5294/? E/Launcher: changeViewByFsGestureState,  view=ShortcutMenuLayer,  alpha=1.0,  scale=1.0

**Comment by unicorn1009** [comment]
> @unicorn1009 加载speex报错了 你把App中的 Speex.getInstance().init(); 注释掉试试，so没加载进去

注释掉后可以进入应用了，但是每次点击视频测试按钮的时候都会闪退。
2019-11-19 17:22:26.952 1384-3171/? E/ActivityTrigger: activityStartTrigger: not whiteListedcom.ggh.video/com.ggh.video.VideoTalkActivity/1
2019-11-19 17:22:26.958 1384-3171/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.ggh.video/com.ggh.video.VideoTalkActivity/1
2019-11-19 17:22:26.969 1384-3171/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.ggh.video/com.ggh.video.VideoTalkActivity/1
2019-11-19 17:22:27.005 954-2143/? E/OMX-VDEC-1080P: Unsupported output color format for c2d (2141391876)
2019-11-19 17:22:27.005 954-2143/? E/OMX-VDEC-1080P: Setting color format failed
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.configureVideoTunnelMode not implemented
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.useAndroidNativeBuffer is supported
2019-11-19 17:22:27.011 954-2143/? E/OMX-VDEC-1080P: get_parameter: unknown param 7f000046
2019-11-19 17:22:27.011 954-2143/? E/OMXNodeInstance: getParameter(0xf2f3aec4:qcom.decoder.avc, ??(0x7f000046)) ERROR: UnsupportedIndex(0x8000101a)
2019-11-19 17:22:27.017 954-2143/? E/OMXNodeInstance: getParameter(0xf2f3aec4:qcom.decoder.avc, ??(0x7f000044)) ERROR: UnsupportedSetting(0x80001019)
2019-11-19 17:22:27.039 22521-22521/com.ggh.video E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.ggh.video, PID: 22521
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ggh.video-rqVFpNiQ4z7iMGjMgK194w==/base.apk"],nativeLibraryDirectories=[/data/app/com.ggh.video-rqVFpNiQ4z7iMGjMgK194w==/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libx264encoder.so"
at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
at java.lang.System.loadLibrary(System.java:1669)
at example.sszpf.x264.x264sdk.(x264sdk.java:32)
at com.ggh.video.encode.X264Encoder.initEncode(X264Encoder.java:39)
at com.ggh.video.encode.X264Encoder.(X264Encoder.java:22)
at com.ggh.video.VideoTalkActivity.onCreate(VideoTalkActivity.java:83)
at android.app.Activity.performCreate(Activity.java:7224)
at android.app.Activity.performCreate(Activity.java:7213)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6806)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2019-11-19 17:22:27.049 2737-2787/? E/octvm_klo: open /data/system/dropbox/system_app_crash@1573815354907.txt for read error, No such file or directory
2019-11-19 17:22:27.074 954-2143/? E/OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
2019-11-19 17:22:27.075 1384-1806/? E/InputDispatcher: channel 'd3ee469 com.ggh.video/com.ggh.video.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-11-19 17:22:27.088 1384-3171/? E/ActivityTrigger: activityResumeTrigger: not whiteListedcom.miui.home/com.miui.home.launcher.Launcher/41201228
2019-11-19 17:22:27.407 5294-5294/? E/Launcher: changeViewByFsGestureState, view=FitSystemWindowView, alpha=1.0, scale=1.0
2019-11-19 17:22:27.407 5294-5294/? E/Launcher: changeViewByFsGestureState, view=ShortcutMenuLayer, alpha=1.0, scale=1.0

**Comment by ManyFish** [comment]
> 
我也遇到了相同的情况，请问有解决吗？

**Comment by xmtggh** [comment]
x

> > 
> 
> 我也遇到了相同的情况，请问有解决吗？

x264 少了64位so所以崩溃了

**Comment by ManyFish** [comment]
> x
> 
> > > 
> > 
> > 
> > 我也遇到了相同的情况，请问有解决吗？
> 
> x264 少了64位so所以崩溃了

您好，我再想问一下，我运行起来后视频通话没有声音，请问该如何修改？运行没有报错。谢谢！！！！
